
URL= https://sixflags-web-uat.sfdev.co/
ParkName=darien
SelectParkTitle=Select a Park | Six Flags
Email=develop@thetunagroup.com
Password=We67B@8us6er
Title=Largest Water & Amusement Parks in Darien Lake | Darien Lake | More characters.................................... | Six Flags Darien Lake
LoginEmail=tunagold@yopmail.com
LoginPassword=Qwerty12345@
