#URL= https://sixflags-web-dev.sfdev.co/
URL= https://uat.sixflags.com/
ParkName=Cedar Point
Email=develop@thetunagroup.com
Password=We67B@8us6er
Title=Largest Water & Amusement Parks in Darien Lake | Darien Lake | More characters.................................... | Six Flags Darien Lake
#LoginEmail=tunagold@yopmail.com
#LoginPassword=Qwerty12345@
SelectParkTitle=Six Flags | Six Flags
#SelectParkTitle=Six Flags: Theme Parks, Roller Coasters & Family Fun Near You | Six Flags
ParkHomeTitle=Six Flags Magic Mountain | Six Flags Magic Mountain
RidesTitle=Rides | Six Flags Magic Mountain
RestaurantsTitle=Restaurants & Dining | Six Flags Magic Mountain
CabanasTitle=Cabanas | Six Flags Magic Mountain
TicketsTitle=Tickets & Passes | Page | Six Flags Magic Mountain

#ParkHomeTitle=Cedar point
#RidesTitle=Rides | Cedar point
#RestaurantsTitle=Restaurants & Dining | Cedar point
#CabanasTitle=Cabanas | Cedar point
#TicketsTitle=Tickets & Passes | Page | Cedar point


FirstName = rahul
LastName = rex
MobileNumber = (647) 384-5453
Dob = 11/01/1997
RetypePassword = Rahuldev1741@
forgot_URL = https://sixflags-web-dev.sfdev.co/account/forgot-password


